#!/usr/bin/env bash
# Refresh the site snapshot the differential test compares against.
#
#   ./scripts/refresh-snapshot.sh
#
# The header is generated here, never hand-written. A hand-maintained date is
# the failure being prevented: refresh the file, forget the header, and the
# differential test goes on comparing the port to a frozen past with a
# timestamp vouching for it.

set -euo pipefail

SOURCE="${SFS_SOURCE:-https://spoilerfreescores.com/}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/site-index.html"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "Fetching $SOURCE"
curl -sSf --max-time 30 "$SOURCE" -o "$TMP"

# Hash the redaction block, not the whole file. Site-wide edits are constant
# and irrelevant here; only a change to this block invalidates the comparison.
BLOCK_SHA="$(python3 - "$TMP" <<'PY'
import sys, hashlib
s = open(sys.argv[1], encoding='utf-8').read()
try:
    a = s.index('const INSIGHT_MAP = {')
    b = s.index('\n  function buildInsightHTML(')
except ValueError:
    sys.exit('Redaction block not found — the site moved it. '
             'Fix the markers in verify.mjs and here before trusting any result.')
print(hashlib.sha256(s[a:b].encode()).hexdigest())
PY
)"

PREV_SHA="$(sed -n 's/^block-sha256: //p' "$OUT" 2>/dev/null | head -1 || true)"

{
  echo "<!-- SNAPSHOT"
  echo "source: $SOURCE"
  echo "fetched: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "block-sha256: $BLOCK_SHA"
  echo "generated by scripts/refresh-snapshot.sh — do not edit by hand"
  echo "-->"
  cat "$TMP"
} > "$OUT"

echo "Wrote $OUT"
echo "block-sha256: $BLOCK_SHA"

if [ -n "$PREV_SHA" ] && [ "$PREV_SHA" != "$BLOCK_SHA" ]; then
  echo
  echo "WARNING: the redaction block changed since the last snapshot."
  echo "  was: $PREV_SHA"
  echo "  now: $BLOCK_SHA"
  echo "Re-run verify.mjs. A differential failure now means the site moved,"
  echo "not that the port drifted — decide which one should change."
fi
